# Set-up

In [1]:
%cd ..

/app


In [17]:
import librosa
import pandas as pd
import numpy as np
import os
import time
import matplotlib.pyplot as plt

from tonami import pitch_process as pp
from tonami import user
from tonami import Utterance as u
from tonami import Classifier as c

In [96]:
# Consts
# USER_TESTING_FILEPATH = 'data/user_audio/testing/'
USER_TESTING_FILEPATH = 'data/users (balanced)/'
DB_THRESHOLD = 10
user_info = user.User(50, 350)
SAMPLERATE = 22050
clf = c.Classifier(4)
clf.load_clf('tonami/data/pickled_svm_80.pkl')

In [97]:
user_audio_dict = {}
raw_data_dict = {}
times_dict = {}

# Run all tasks (long)

In [98]:
# get all files
filenames = os.listdir(USER_TESTING_FILEPATH)
num_files = len(filenames)

user_audio_dict['Filename'] = filenames

In [99]:
# get target tones
targets = [0] * num_files

for i, filename in enumerate(filenames):
    # if i > 2:
    #     targets[i] = int(filename.split("_")[1][-1])
    
    targets[i] = int(filename.split("_")[0][-1])

user_audio_dict['Target'] = targets

In [100]:
# load files
time_series_arr = [None] * num_files
load_times = [0] * num_files

for i, filename in enumerate(filenames):
    start = time.time()
    time_series_arr[i], _ = librosa.load(USER_TESTING_FILEPATH + filename)  
    load_times[i] = time.time() - start

raw_data_dict['Time Series'] = time_series_arr
times_dict['load'] = load_times

In [101]:
# get durations
durations = [0] * num_files

for i, time_series in enumerate(time_series_arr):
    durations[i] = len(time_series)/SAMPLERATE

user_audio_dict['Durations'] = durations

In [102]:
# trim files
f_time_series_arr = [None] * num_files
trim_times = [0] * num_files

for i, time_series in enumerate(time_series_arr):
    start = time.time()
    f_time_series_arr[i], _ = librosa.effects.trim(y=time_series, top_db=DB_THRESHOLD) 
    trim_times[i] = time.time() - start

raw_data_dict['Filtered Time Series'] = f_time_series_arr
times_dict['trim'] = trim_times

In [103]:
# get filtered durations
f_durations = [0] * num_files

for i, f_time_series in enumerate(f_time_series_arr):
    f_durations[i] = len(f_time_series)/SAMPLERATE

user_audio_dict['Filtered Durations'] = f_durations

In [85]:
# get pitch contours
pitch_contour_arr = [None] * num_files
contour_times = [0] * num_files

for i, f_time_series in enumerate(f_time_series_arr):
    start = time.time()
    pitch_contour_arr[i] , _, _ = librosa.pyin(f_time_series, fmin=50, fmax=400)
    contour_times[i] = time.time() - start

raw_data_dict['Pitch Contours'] = pitch_contour_arr
times_dict['contour'] = contour_times

In [86]:
# Tonami's feature extraction   
normalized_pitch_arr = [None] * num_files
nans_arr = [None] * num_files
features_arr = [None] * num_files
extraction_times = [0] * num_files

for i, pitch_contour in enumerate(pitch_contour_arr):
    start = time.time()
    interp, nans_arr[i] = pp.preprocess(pitch_contour)
    interp_np = np.array([interp], dtype=float)
    profile = test_user.get_pitch_profile()
    avgd = pp.moving_average(interp_np)
    normalized_pitch = pp.normalize_pitch(avgd, profile['max_f0'], profile['min_f0'])
    features_arr[i] = np.array([pp.basic_feat_calc(normalized_pitch[0])])
    normalized_pitch_arr[i] = normalized_pitch
    extraction_times[i] = time.time() - start
    
raw_data_dict['Normalized Pitch'] = normalized_pitch_arr
raw_data_dict['Nans'] = nans_arr
raw_data_dict['Features'] = features_arr
times_dict['extraction'] = extraction_times

In [87]:
# Classifier time (svm_80_lda)
class_times = [0] * num_files
classified_tones = [0] * num_files
classified_probs = [None] * num_files
classification_errors = 0;

for i, features in enumerate(features_arr):
    start = time.time()
    try:
        classified_tones[i], classified_probs[i] = clf.classify_tones(features)
    except:
        classification_errors += 1
    class_times[i] = time.time() - start

user_audio_dict['Classified Tones'] = classified_tones
user_audio_dict['Classified Probs'] = classified_probs
times_dict['class'] = class_times

In [95]:
# Get rating
rating_times = [0] * num_files
ratings_arr = [""] * num_files

for i, clf_probs in enumerate(classified_probs):
    start = time.time()
    try:
        print(clf_probs[0])
        target_prob = clf_probs[0][targets[i]-1]

        # if the probability of any other tone is >= 90%, return try again
        for prob in clf_probs[0][np.arange(len(clf_probs[0]))!=(targets[i]-1)]:
            if prob >= 0.9:
                ratings_arr[i] = "Not quite, try again?"

        # if your target probability is more than 50%, you are good
        if target_prob > 0.5:
            ratings_arr[i] = "Great job!"
        else:
            ratings_arr[i] = "Almost there!"
    except:
        ratings_arr[i] = "Unavailable"
    rating_times[i] = time.time() - start

user_audio_dict['Rating'] = ratings_arr
times_dict['rate'] = rating_times

[8.19681778e-08 3.91351620e-08 9.99770256e-01 2.29623285e-04]
[9.79727212e-01 1.90165924e-04 2.79225700e-03 1.72903647e-02]
[9.78796511e-01 1.26304126e-04 3.24547260e-03 1.78317123e-02]
[0.5586142  0.00183959 0.08440883 0.35513738]
[0.70857033 0.02865544 0.21544539 0.04732884]
[9.27435016e-08 1.02779770e-07 9.99713736e-01 2.86068943e-04]
[0.80652717 0.00732524 0.04691233 0.13923526]
[9.75282453e-01 2.14989851e-04 6.65757661e-03 1.78449801e-02]
[7.37517949e-07 2.95878964e-07 9.99420182e-01 5.78784629e-04]
[3.38072391e-03 2.26095928e-04 9.93442804e-01 2.95037663e-03]
[1.20523416e-03 1.80274373e-05 9.76468925e-01 2.23078131e-02]
[3.40352126e-08 1.84275089e-08 3.67318983e-08 9.99999911e-01]
[1.67863634e-07 5.93385163e-08 7.23856274e-08 9.99999700e-01]
[9.76441261e-01 5.76805622e-04 1.02684992e-02 1.27134341e-02]
[2.25174493e-03 5.64035311e-04 9.94102189e-01 3.08203064e-03]
[0.32284519 0.10349621 0.22643181 0.34722679]
[8.93826255e-01 1.46384574e-04 2.50745333e-03 1.03519907e-01]
[3.1970238

In [ ]:
# Processing time (svm_80_lda)    
process_times = [0] * num_files

for i, filename in enumerate(filenames):
    start = time.time()
    user_utterance = u.Utterance(filename=USER_TESTING_FILEPATH + filename)
    _, _, features = user_utterance.pre_process(user_info)
    try:
        _, _ = clf.classify_tones(features)
    except:
        pass
    process_times[i] = time.time() - start

times_dict['total'] = process_times

# All generated data

In [104]:
# consolidate data
user_audio_df = pd.DataFrame(user_audio_dict)
raw_data_df = pd.DataFrame(raw_data_dict)
times_df = pd.DataFrame(times_dict)

## With Outliers

In [105]:
pd.set_option('display.max_rows', None)

In [106]:
display(user_audio_df)

Filename  Target  Durations  Filtered Durations
0      ba1_HV1_ex8_R2_user-testing.mp3       1       3.98            0.278639
1      ba1_LV3_ex8_R4_user-testing.mp3       1       1.34            0.255420
2      ba1_LV6_ex8_R1_user-testing.mp3       1       2.12            0.301859
3    bao3_HV4_ex20_R1_user-testing.mp3       3       2.24            0.696599
4    bao3_LV6_ex20_R2_user-testing.mp3       3       2.54            0.650159
5   bing1_HV1_ex16_R2_user-testing.mp3       1       2.82            0.325079
6   bing1_LV2_ex16_R1_user-testing.mp3       1       4.94            1.160998
7   bing1_LV6_ex16_R3_user-testing.mp3       1       1.84            0.208980
8      fa1_HV1_ex3_R1_user-testing.mp3       1       3.92            0.580499
9      fa1_HV4_ex3_R1_user-testing.mp3       1       2.24            0.348299
10     fa2_HV4_ex1_R1_user-testing.mp3       2       3.12            0.673379
11     fa2_LV5_ex1_R3_user-testing.mp3       2       3.72            0.650159
12    fa2_LV6_ex21_R5_user-testing.mp3       2       2.88            0.580499
13     fa3_HV1_ex2_R1_user-testing.mp3       3       4.84            0.417959
14     fa3_HV4_ex2_R2_user-testing.mp3       3       2.92            0.441179
15    fa3_LV3_ex22_R2_user-testing.mp3       3       1.96            0.464399
16    fa3_LV5_ex22_R1_user-testing.mp3       3       2.88            0.487619
17     fa4_HV3_ex4_R1_user-testing.mp3       4       2.60            0.371519
18    fa4_LV1_ex24_R2_user-testing.mp3       4       2.40            0.232200
19     fa4_LV1_ex4_R1_user-testing.mp3       4       2.88            0.325079
20    fa4_LV3_ex24_R1_user-testing.mp3       4       2.80            0.232200
21    fu2_LV2_ex14_R1_user-testing.mp3       2       3.20            0.626939
22    gan4_LV1_ex9_R1_user-testing.mp3       4       2.60            0.208980
23    la1_HV3_ex13_R1_user-testing.mp3       1       1.70            0.701542
24    la1_LV2_ex13_R2_user-testing.mp3       1       2.42            0.626939
25    la1_LV5_ex13_R6_user-testing.mp3       1       2.70            0.626939
26    li3_LV1_ex11_R1_user-testing.mp3       3       2.60            0.905578
27    li3_LV5_ex11_R4_user-testing.mp3       3       1.96            0.882358
28   ming2_HV1_ex5_R2_user-testing.mp3       2       3.20            0.510839
29   ming2_HV2_ex5_R1_user-testing.mp3       2       4.32            1.346757
30   ming2_LV2_ex5_R1_user-testing.mp3       2       3.30            0.557279
31    ni2_LV3_ex17_R1_user-testing.mp3       2       2.00            0.580499
32   rou4_HV2_ex15_R2_user-testing.mp3       4       2.46            0.255420
33   rou4_HV3_ex15_R1_user-testing.mp3       4       2.40            0.394739
34   rou4_LV1_ex15_R5_user-testing.mp3       4       3.32            0.255420
35   rou4_LV4_ex15_R3_user-testing.mp3       4       1.52            0.255420
36    tu4_HV2_ex18_R1_user-testing.mp3       4       2.30            0.417959
37    wan2_HV2_ex6_R1_user-testing.mp3       2       2.78            0.417959
38    wan2_HV4_ex6_R2_user-testing.mp3       2       2.84            0.417959
39    wan2_LV3_ex6_R1_user-testing.mp3       2       1.60            0.348299
40    wan2_LV4_ex6_R1_user-testing.mp3       2       3.24            0.487619
41     wo3_HV2_ex7_R1_user-testing.mp3       3       2.96            0.603719
42     wo3_LV1_ex7_R1_user-testing.mp3       3       3.48            0.394739
43    wu3_HV3_ex10_R1_user-testing.mp3       3       1.96            0.905578
44    wu3_LV2_ex10_R1_user-testing.mp3       3       2.50            0.650159
45    wu3_LV4_ex10_R1_user-testing.mp3       3       4.38            0.719819
46    ya1_HV3_ex12_R3_user-testing.mp3       1       2.64            0.743039
47    ya1_LV3_ex12_R2_user-testing.mp3       1       1.52            0.510839
48  yang4_LV4_ex19_R2_user-testing.mp3       4       3.10            0.278639
49  yang4_LV5_ex19_R7_user-testing.mp3       4       2.54            0.348299

In [ ]:
n, bins, _ = plt.hist(user_audio_df['Durations'])
plt.show() 
print(n)
print(bins)

In [ ]:
plt.scatter(user_audio_df['Durations'], times_df['load'])
plt.show()

In [ ]:
n, bins, _ = plt.hist(user_audio_df['Filtered Durations'])
plt.show() 
print(n)
print(bins)

In [ ]:
plt.scatter(user_audio_df['Filtered Durations'], times_df['contour'])
plt.show()

### Raw Data

In [91]:
display(raw_data_df)

Time Series  \
0   [-2.2323418e-05, -9.556377e-06, -2.1398931e-05...   
1   [1.6478629e-07, -1.6929025e-07, 1.6652986e-07,...   
2   [5.593205e-08, -4.320672e-08, 2.5254167e-08, -...   
3   [-4.7085686e-07, 1.6121598e-05, -2.965797e-05,...   
4   [1.4438017e-07, -1.4551632e-07, 1.4012384e-07,...   
5   [1.7059865e-05, 8.577302e-06, 3.66678e-08, -1....   
6   [9.263582e-06, 8.813827e-06, -3.856561e-06, 3....   
7   [5.3673226e-08, -6.89991e-08, 8.60138e-08, -1....   
8   [-9.860878e-06, 1.4507506e-05, 1.2650449e-05, ...   
9   [-3.186856e-05, 1.1959399e-05, -1.5235764e-05,...   
10  [-1.16735734e-07, 1.06682e-07, -8.851964e-08, ...   
11  [1.5806201e-07, -1.6289215e-07, 1.613357e-07, ...   
12  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
13  [2.3403322e-07, -1.8439309e-07, 1.1291058e-07,...   
14  [1.2543437e-07, -1.3282177e-07, 1.3598131e-07,...   
15  [-2.5626778e-07, 2.870843e-07, -3.15078e-07, 3...   
16  [1.1545933e-07, -1.2428895e-07, 1.2962812e-07,...   
17  [2.143026e-06, -1.9899344e-06, 1.3076072e-06, ...   
18  [1.4081498e-08, 4.4713836e-08, -1.1749112e-07,...   
19  [-1.550862e-05, -1.3107829e-05, 1.6517479e-05,...   
20  [-8.3496175e-08, 1.1121802e-07, -1.4070605e-07...   
21  [1.3724379e-07, -1.6305208e-07, 1.87744e-07, -...   
22  [7.316672e-08, -7.8282945e-08, 8.0800866e-08, ...   
23  [3.3425113e-07, -3.6066146e-07, 3.7712715e-07,...   
24  [8.937929e-07, -7.623803e-07, 4.0768236e-07, 5...   
25  [-3.0844933e-09, -2.0809473e-08, 5.1349357e-08...   
26  [8.7271324e-08, -1.04370265e-07, 1.2081979e-07...   
27  [2.5848316e-05, 2.0558962e-05, -8.8678576e-07,...   
28  [-4.2303835e-08, 5.5473503e-08, -6.955169e-08,...   
29  [1.0257453e-07, -1.0736355e-07, 1.0828071e-07,...   
30  [5.1591798e-08, -4.8940674e-08, 4.3830827e-08,...   
31  [2.4729165e-09, -3.4914847e-09, 4.6962176e-09,...   
32  [-1.2192693e-07, 9.619645e-08, -5.9014628e-08,...   
33  [3.1080237e-06, 5.2675214e-06, -1.1648876e-05,...   
34  [4.6437202e-05, 2.529268e-05, 1.35565015e-05, ...   
35  [1.4681727e-05, -9.448502e-07, 1.6992223e-06, ...   
36  [-9.728042e-06, -5.524428e-06, 7.3989545e-06, ...   
37  [5.187272e-08, -3.7137546e-08, 1.6588393e-08, ...   
38  [1.0997356e-07, -1.3231664e-07, 1.5438424e-07,...   
39  [-1.2240927e-08, 1.6384847e-08, -2.0137014e-08...   
40  [-1.9525225e-05, -2.5425485e-05, 6.967256e-06,...   
41  [4.8480314e-07, -6.155815e-07, 7.5544153e-07, ...   
42  [4.0045527e-09, -2.5451214e-08, 5.199523e-08, ...   
43  [-1.1068761e-05, -1.0495082e-05, -3.4796765e-0...   
44  [-6.705385e-08, 6.15419e-08, -5.175338e-08, 3....   
45  [1.3386413e-05, 1.9156592e-05, 5.5702293e-07, ...   
46  [1.6359851e-07, -1.3638731e-07, 9.1966434e-08,...   
47  [-1.5633441e-07, 1.3424169e-07, -9.5771085e-08...   
48  [-1.4008072e-07, 1.3419891e-07, -1.196462e-07,...   
49  [1.9735681e-07, -1.571733e-07, 9.8408094e-08, ...   

                                 Filtered Time Series  \
0   [0.008356462, 0.0073015993, 0.0058155973, 0.00...   
1   [-0.0084268525, -0.006313884, -0.0023718618, -...   
2   [-0.01579637, -0.0017586777, -0.0072183996, -0...   
3   [0.16149397, 0.16343096, 0.14990065, 0.1235436...   
4   [-0.02786146, -0.022654438, -0.017134013, -0.0...   
5   [0.0173583, 0.03505041, 0.06005359, 0.05949120...   
6   [-0.013737056, -0.016202377, -0.0030810894, 0....   
7   [2.0850384e-06, -2.4053743e-05, -3.3571647e-05...   
8   [0.001696023, -0.0022924992, 0.001871909, -0.0...   
9   [-0.017877454, -0.019538423, -0.037981894, -0....   
10  [-0.0013519217, 0.0029539915, -0.000442203, 0....   
11  [0.008104552, 0.01287494, 0.010058287, -0.0026...   
12  [0.007089484, 0.013520438, 0.018755013, 0.0127...   
13  [0.0027017172, 0.0022272626, -0.00011175546, -...   
14  [-0.02283696, 0.014995136, -0.02310556, -0.013...   
15  [-0.0091147395, -0.0051184837, -0.006392412, -...   
16  [-0.0015223988, -0.0021027958, -0.0035595992, ...   
17  [0.0076603875, -0.0022980017, 0.0013040119, -0...   
18  [0.039636612, 0.058223367, 0.019592335, 0.0060.

In [94]:
error_rows = raw_data_df[user_audio_df['Classified Tones'] == 0]
display(error_rows)

Time Series  \
18  [1.4081498e-08, 4.4713836e-08, -1.1749112e-07,...   
19  [-1.550862e-05, -1.3107829e-05, 1.6517479e-05,...   
22  [7.316672e-08, -7.8282945e-08, 8.0800866e-08, ...   
26  [8.7271324e-08, -1.04370265e-07, 1.2081979e-07...   
34  [4.6437202e-05, 2.529268e-05, 1.35565015e-05, ...   
42  [4.0045527e-09, -2.5451214e-08, 5.199523e-08, ...   
48  [-1.4008072e-07, 1.3419891e-07, -1.196462e-07,...   

                                 Filtered Time Series  \
18  [0.039636612, 0.058223367, 0.019592335, 0.0060...   
19  [-0.030242397, -0.06909699, 0.008794107, 0.014...   
22  [0.00043815587, 0.001019749, -2.2616014e-05, -...   
26  [-0.0053558517, -0.022193376, -0.0077437153, 0...   
34  [-0.02716355, -0.015015244, -0.003392055, 0.00...   
42  [0.00064278016, 0.0008164294, 0.00034824703, 0...   
48  [0.0035159409, 0.0021071385, 0.004613428, 0.00...   

                                       Pitch Contours  \
18  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
19  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
22  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
26  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
34  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
42  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
48  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   

                                     Normalized Pitch  \
18  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
19  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
22  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
26  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
34  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
42  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   
48  [[nan, nan, nan, nan, nan, nan, nan, nan, nan,...   

                                                 Nans  \
18  [True, True, True, True, True, True, True, Tru...   
19  [True, True, True, True, True, True, True, Tru...   
22  [True, True, True, True, True, True, True, Tru...   
26  [True, True, True, True, True, True, True, Tru...   
34  [True, True, True, True, True, True, True, Tru...   
42  [True, True, True, True, True, True, True, Tru...   
48  [True, True, True, True, True, True, True, Tru...   

                            Features  
18  [[nan, nan, nan, nan, nan, nan]]  
19  [[nan, nan, nan, nan, nan, nan]]  
22  [[nan, nan, nan, nan, nan, nan]]  
26  [[nan, nan, nan, nan, nan, nan]]  
34  [[nan, nan, nan, nan, nan, nan]]  
42  [[nan, nan, nan, nan, nan, nan]]  
48  [[nan, nan, nan, nan, nan, nan]]

### Times

In [ ]:
display(times_df)

## Without Outliers

In [ ]:
outliers = user_audio_df[user_audio_df['Filtered Durations'] > 0.8].index
print("Num of outliers: ", len(outliers))
user_audio_df_fix = user_audio_df.drop(outliers)
raw_data_df_fix = raw_data_df.drop(outliers)
times_df_fix = times_df.drop(outliers)

### User Audio

In [ ]:
n, bins, _ = plt.hist(user_audio_df_fix['Filtered Durations'])
plt.show() 
print(n)
print(bins)

# Report

In [ ]:
# File report
print("Audio File Statistics")
print("Quantity :", user_audio_df.shape[0])
print("Duration :", "%.2f" % round(user_audio_df['Durations'].mean(), 2), u"\u00B1", "%.2f" % round(user_audio_df['Durations'].std(), 2) )
print("Filtered :", "%.2f" % round(user_audio_df['Filtered Durations'].mean(), 2), u"\u00B1", "%.2f" % round(user_audio_df['Filtered Durations'].std(), 2) )
print("\n")

print("Audio File Statistics (w/o outliers)")
print("Quantity :", user_audio_df_fix.shape[0])
print("Duration :", "%.2f" % round(user_audio_df_fix['Durations'].mean(), 2), u"\u00B1", "%.2f" % round(user_audio_df_fix['Durations'].std(), 2) )
print("Filtered :", "%.2f" % round(user_audio_df_fix['Filtered Durations'].mean(), 2), u"\u00B1", "%.2f" % round(user_audio_df_fix['Filtered Durations'].std(), 2) )

In [ ]:
# Time breakdown reports
print("Task Time Statistics (microseconds)")
for name, values in times_df.items():
    print("%10s :" % name, 
          "%6i" % (values.mean()*1000000), 
          u"\u00B1", 
          "%6i" % (values.std()*1000000)
         )    
print("\n")

print("Task Time Statistics (w/o outliers) (microseconds)")
for name, values in times_df_fix.items():
    print("%10s :" % name, 
          "%6i" % (values.mean()*1000000),
          u"\u00B1", 
          "%6i" % (values.std()*1000000)
         )

In [38]:
print("Classification errors: ", classification_errors)

Classification errors:  64
